word: wordAnalyse.cpp makefile ../program
	clang++ -o wordAnalyse wordAnalyse.cpp
	make runWordAnalyse
runWordAnalyse:
	./wordAnalyse
	echo "\t================log analyse============"
	cat ../log/.wAnalyse
	echo "\t================log err================"
	cat ../log/.err
